name: regms_flutter_client
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  http:
  simple_animations: ^5.0.2
  expandable_page_view: ^1.0.17
  google_fonts: ^6.2.1
  flutter_svg: ^2.0.10+1
  flutter_verification_code: ^1.1.3+1
  shared_preferences: ^2.0.15
  video_player: ^2.4.7
  provider:
  mobx: ^2.3.3+2
  flutter_mobx: ^2.2.1+1
  camera: ^0.11.0+2
  flutter_slidable: ^3.1.1
  dio: ^5.6.0
  json_annotation: ^4.7.0

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.3.2
  json_serializable: ^6.5.3

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/videos/
    - assets/lang/